2024-04-23 21:58:15,896 INFO    StreamThr :6140 [internal.py:wandb_internal():86] W&B internal server running at pid: 6140, started at: 2024-04-23 21:58:15.895174
2024-04-23 21:58:15,901 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status
2024-04-23 21:58:15,906 INFO    WriterThread:6140 [datastore.py:open_for_write():87] open: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/run-b7v20mk3.wandb
2024-04-23 21:58:15,907 DEBUG   SenderThread:6140 [sender.py:send():379] send: header
2024-04-23 21:58:15,943 DEBUG   SenderThread:6140 [sender.py:send():379] send: run
2024-04-23 21:58:16,586 INFO    SenderThread:6140 [dir_watcher.py:__init__():211] watching files in: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files
2024-04-23 21:58:16,586 INFO    SenderThread:6140 [sender.py:_start_run_threads():1124] run started: b7v20mk3 with start time 1713880695.895797
2024-04-23 21:58:16,606 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: check_version
2024-04-23 21:58:16,606 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: check_version
2024-04-23 21:58:19,276 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: run_start
2024-04-23 21:58:19,286 DEBUG   HandlerThread:6140 [system_info.py:__init__():26] System info init
2024-04-23 21:58:19,286 DEBUG   HandlerThread:6140 [system_info.py:__init__():41] System info init done
2024-04-23 21:58:19,286 INFO    HandlerThread:6140 [system_monitor.py:start():194] Starting system monitor
2024-04-23 21:58:19,287 INFO    HandlerThread:6140 [system_monitor.py:probe():214] Collecting system info
2024-04-23 21:58:19,287 INFO    SystemMonitor:6140 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-23 21:58:19,288 DEBUG   HandlerThread:6140 [system_info.py:probe():150] Probing system
2024-04-23 21:58:19,290 INFO    SystemMonitor:6140 [interfaces.py:start():190] Started cpu monitoring
2024-04-23 21:58:19,291 INFO    SystemMonitor:6140 [interfaces.py:start():190] Started disk monitoring
2024-04-23 21:58:19,293 INFO    SystemMonitor:6140 [interfaces.py:start():190] Started gpuapple monitoring
2024-04-23 21:58:19,294 INFO    SystemMonitor:6140 [interfaces.py:start():190] Started memory monitoring
2024-04-23 21:58:19,301 INFO    SystemMonitor:6140 [interfaces.py:start():190] Started network monitoring
2024-04-23 21:58:19,303 DEBUG   HandlerThread:6140 [system_info.py:_probe_git():135] Probing git
2024-04-23 21:58:19,334 DEBUG   HandlerThread:6140 [system_info.py:_probe_git():143] Probing git done
2024-04-23 21:58:19,335 DEBUG   HandlerThread:6140 [system_info.py:probe():198] Probing system done
2024-04-23 21:58:19,335 DEBUG   HandlerThread:6140 [system_monitor.py:probe():223] {'os': 'macOS-14.2.1-arm64-arm-64bit', 'python': '3.10.13', 'heartbeatAt': '2024-04-23T13:58:19.288802', 'startedAt': '2024-04-23T13:58:15.878671', 'docker': None, 'cuda': None, 'args': ('--model_name_or_path', '/Users/a58/Downloads/pretrain_model/Qwen/Qwen1.5-0.5B-Chat', '--do_train', 'True', '--per_device_train_batch_size', '4', '--gradient_accumulation_steps', '1', '--learning_rate', '5e-5', '--weight_decay', '0', '--max_grad_norm', '1.0', '--num_train_epochs', '1.0', '--block_size', '32', '--train_file', '/Users/a58/Downloads/my_test/data/data_sft/renting_data_train_7000_improved_prompting3.json', '--output_dir', '/Users/a58/Downloads/MoE_Train/outputs', '--overwrite_output_dir', '--logging_dir', '/Users/a58/Downloads/MoE_Train/outputs', '--save_strategy', 'epoch', '--save_total_limit', '1', '--logging_strategy', 'steps', '--logging_steps', '1', '--report_to', 'wandb', '--trust_remote_code', 'True', '--template', 'qwen', '--q_lora', 'False', '--use_lora', 'True', '--lora_r', '8', '--lora_alpha', '32', '--lora_dropout', '0.05', '--lora_target_modules', 'q_proj', 'v_proj', 'k_proj', 'o_proj', 'gate_proj', 'down_proj', 'up_proj'), 'state': 'running', 'program': '/Users/a58/Downloads/MoE_Train/finetune/run.py', 'codePathLocal': 'run.py', 'codePath': 'finetune/run.py', 'git': {'remote': 'https://github.com/Darrenzeng/MoE_Train.git', 'commit': '5769742f6f9e686c6324ed68457139359bbaa7b0'}, 'email': 'zengyufei@58.com', 'root': '/Users/a58/Downloads/MoE_Train', 'host': '58deMacBook-Pro-2.local', 'username': 'a58', 'executable': '/Users/a58/anaconda3/envs/llama_factory/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 13.368824005126953}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2024-04-23 21:58:19,335 INFO    HandlerThread:6140 [system_monitor.py:probe():224] Finished collecting system info
2024-04-23 21:58:19,335 INFO    HandlerThread:6140 [system_monitor.py:probe():227] Publishing system info
2024-04-23 21:58:19,335 DEBUG   HandlerThread:6140 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-04-23 21:58:19,605 INFO    Thread-17 :6140 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/conda-environment.yaml
2024-04-23 21:58:22,841 DEBUG   HandlerThread:6140 [system_info.py:_save_conda():222] Saving conda packages done
2024-04-23 21:58:22,842 INFO    HandlerThread:6140 [system_monitor.py:probe():229] Finished publishing system info
2024-04-23 21:58:22,846 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status_report
2024-04-23 21:58:22,846 DEBUG   SenderThread:6140 [sender.py:send():379] send: files
2024-04-23 21:58:22,846 INFO    SenderThread:6140 [sender.py:_save_file():1390] saving file wandb-metadata.json with policy now
2024-04-23 21:58:23,229 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: python_packages
2024-04-23 21:58:23,229 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: python_packages
2024-04-23 21:58:23,231 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: stop_status
2024-04-23 21:58:23,231 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: stop_status
2024-04-23 21:58:23,233 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-23 21:58:23,617 INFO    Thread-17 :6140 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/conda-environment.yaml
2024-04-23 21:58:23,617 INFO    Thread-17 :6140 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/wandb-metadata.json
2024-04-23 21:58:23,618 INFO    Thread-17 :6140 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/requirements.txt
2024-04-23 21:58:23,630 DEBUG   SenderThread:6140 [sender.py:send():379] send: telemetry
2024-04-23 21:58:23,631 DEBUG   SenderThread:6140 [sender.py:send():379] send: config
2024-04-23 21:58:23,632 DEBUG   SenderThread:6140 [sender.py:send():379] send: metric
2024-04-23 21:58:23,632 DEBUG   SenderThread:6140 [sender.py:send():379] send: telemetry
2024-04-23 21:58:23,632 DEBUG   SenderThread:6140 [sender.py:send():379] send: metric
2024-04-23 21:58:23,633 WARNING SenderThread:6140 [sender.py:send_metric():1341] Seen metric with glob (shouldn't happen)
2024-04-23 21:58:23,633 DEBUG   SenderThread:6140 [sender.py:send():379] send: telemetry
2024-04-23 21:58:24,623 INFO    Thread-17 :6140 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/output.log
2024-04-23 21:58:24,663 INFO    wandb-upload_0:6140 [upload_job.py:push():131] Uploaded file /var/folders/0t/wpjq3m9x0s39k2ngjkd8dqj80000gn/T/tmp6i2cr_ipwandb/bkxwycqb-wandb-metadata.json
2024-04-23 21:58:26,634 INFO    Thread-17 :6140 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/output.log
2024-04-23 21:58:26,646 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status_report
2024-04-23 21:58:31,670 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status_report
2024-04-23 21:58:36,694 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status_report
2024-04-23 21:58:38,263 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: stop_status
2024-04-23 21:58:38,269 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-23 21:58:38,277 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: stop_status
2024-04-23 21:58:42,190 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status_report
2024-04-23 21:58:47,884 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status_report
2024-04-23 21:58:50,120 INFO    Thread-17 :6140 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/config.yaml
2024-04-23 21:58:53,254 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: stop_status
2024-04-23 21:58:53,404 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-23 21:58:53,408 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: stop_status
2024-04-23 21:58:54,757 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status_report
2024-04-23 21:58:59,768 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status_report
2024-04-23 21:58:59,893 DEBUG   SenderThread:6140 [sender.py:send():379] send: exit
2024-04-23 21:59:00,429 INFO    SenderThread:6140 [sender.py:send_exit():586] handling exit code: 1
2024-04-23 21:59:00,439 INFO    SenderThread:6140 [sender.py:send_exit():588] handling runtime: 40
2024-04-23 21:59:00,439 INFO    SenderThread:6140 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-04-23 21:59:00,439 INFO    SenderThread:6140 [sender.py:send_exit():594] send defer
2024-04-23 21:59:00,440 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: defer
2024-04-23 21:59:00,440 INFO    HandlerThread:6140 [handler.py:handle_request_defer():172] handle defer: 0
2024-04-23 21:59:00,442 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: defer
2024-04-23 21:59:00,444 INFO    SenderThread:6140 [sender.py:send_request_defer():610] handle sender defer: 0
2024-04-23 21:59:00,444 INFO    SenderThread:6140 [sender.py:transition_state():614] send defer: 1
2024-04-23 21:59:00,444 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: defer
2024-04-23 21:59:00,444 INFO    HandlerThread:6140 [handler.py:handle_request_defer():172] handle defer: 1
2024-04-23 21:59:00,445 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: defer
2024-04-23 21:59:00,445 INFO    SenderThread:6140 [sender.py:send_request_defer():610] handle sender defer: 1
2024-04-23 21:59:00,445 INFO    SenderThread:6140 [sender.py:transition_state():614] send defer: 2
2024-04-23 21:59:00,445 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: defer
2024-04-23 21:59:00,445 INFO    HandlerThread:6140 [handler.py:handle_request_defer():172] handle defer: 2
2024-04-23 21:59:00,445 INFO    HandlerThread:6140 [system_monitor.py:finish():203] Stopping system monitor
2024-04-23 21:59:00,452 INFO    HandlerThread:6140 [interfaces.py:finish():202] Joined cpu monitor
2024-04-23 21:59:00,452 INFO    HandlerThread:6140 [interfaces.py:finish():202] Joined disk monitor
2024-04-23 21:59:00,453 DEBUG   SystemMonitor:6140 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-23 21:59:00,454 DEBUG   SystemMonitor:6140 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-23 21:59:00,454 DEBUG   SystemMonitor:6140 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-23 21:59:00,613 INFO    HandlerThread:6140 [interfaces.py:finish():202] Joined gpuapple monitor
2024-04-23 21:59:00,614 INFO    HandlerThread:6140 [interfaces.py:finish():202] Joined memory monitor
2024-04-23 21:59:00,614 INFO    HandlerThread:6140 [interfaces.py:finish():202] Joined network monitor
2024-04-23 21:59:00,614 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: defer
2024-04-23 21:59:00,614 INFO    SenderThread:6140 [sender.py:send_request_defer():610] handle sender defer: 2
2024-04-23 21:59:00,614 INFO    SenderThread:6140 [sender.py:transition_state():614] send defer: 3
2024-04-23 21:59:00,614 DEBUG   SenderThread:6140 [sender.py:send():379] send: telemetry
2024-04-23 21:59:00,614 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: defer
2024-04-23 21:59:00,615 DEBUG   SenderThread:6140 [sender.py:send():379] send: stats
2024-04-23 21:59:00,615 INFO    HandlerThread:6140 [handler.py:handle_request_defer():172] handle defer: 3
2024-04-23 21:59:00,616 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: defer
2024-04-23 21:59:00,616 INFO    SenderThread:6140 [sender.py:send_request_defer():610] handle sender defer: 3
2024-04-23 21:59:00,616 INFO    SenderThread:6140 [sender.py:transition_state():614] send defer: 4
2024-04-23 21:59:00,616 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: defer
2024-04-23 21:59:00,616 INFO    HandlerThread:6140 [handler.py:handle_request_defer():172] handle defer: 4
2024-04-23 21:59:00,616 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: defer
2024-04-23 21:59:00,616 INFO    SenderThread:6140 [sender.py:send_request_defer():610] handle sender defer: 4
2024-04-23 21:59:00,616 INFO    SenderThread:6140 [sender.py:transition_state():614] send defer: 5
2024-04-23 21:59:00,616 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: defer
2024-04-23 21:59:00,616 INFO    HandlerThread:6140 [handler.py:handle_request_defer():172] handle defer: 5
2024-04-23 21:59:00,617 DEBUG   SenderThread:6140 [sender.py:send():379] send: summary
2024-04-23 21:59:00,617 INFO    SenderThread:6140 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-04-23 21:59:00,617 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: defer
2024-04-23 21:59:00,617 INFO    SenderThread:6140 [sender.py:send_request_defer():610] handle sender defer: 5
2024-04-23 21:59:00,617 INFO    SenderThread:6140 [sender.py:transition_state():614] send defer: 6
2024-04-23 21:59:00,617 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: defer
2024-04-23 21:59:00,617 INFO    HandlerThread:6140 [handler.py:handle_request_defer():172] handle defer: 6
2024-04-23 21:59:00,618 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: defer
2024-04-23 21:59:00,618 INFO    SenderThread:6140 [sender.py:send_request_defer():610] handle sender defer: 6
2024-04-23 21:59:00,624 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status_report
2024-04-23 21:59:00,958 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:00,958 INFO    SenderThread:6140 [sender.py:transition_state():614] send defer: 7
2024-04-23 21:59:00,959 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:00,959 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: defer
2024-04-23 21:59:00,960 INFO    HandlerThread:6140 [handler.py:handle_request_defer():172] handle defer: 7
2024-04-23 21:59:00,960 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: defer
2024-04-23 21:59:00,960 INFO    SenderThread:6140 [sender.py:send_request_defer():610] handle sender defer: 7
2024-04-23 21:59:01,150 INFO    Thread-17 :6140 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/output.log
2024-04-23 21:59:01,150 INFO    Thread-17 :6140 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/config.yaml
2024-04-23 21:59:01,151 INFO    Thread-17 :6140 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/wandb-summary.json
2024-04-23 21:59:01,960 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:02,471 INFO    SenderThread:6140 [sender.py:transition_state():614] send defer: 8
2024-04-23 21:59:02,471 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:02,471 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: defer
2024-04-23 21:59:02,471 INFO    HandlerThread:6140 [handler.py:handle_request_defer():172] handle defer: 8
2024-04-23 21:59:02,472 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: defer
2024-04-23 21:59:02,472 INFO    SenderThread:6140 [sender.py:send_request_defer():610] handle sender defer: 8
2024-04-23 21:59:02,472 INFO    SenderThread:6140 [job_builder.py:build():318] Attempting to build job artifact
2024-04-23 21:59:02,476 INFO    SenderThread:6140 [job_builder.py:_get_source_type():455] is repo sourced job
2024-04-23 21:59:02,967 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:03,160 INFO    Thread-17 :6140 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/output.log
2024-04-23 21:59:03,714 INFO    SenderThread:6140 [job_builder.py:build():431] adding wandb-job metadata file
2024-04-23 21:59:03,743 INFO    SenderThread:6140 [sender.py:transition_state():614] send defer: 9
2024-04-23 21:59:03,743 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:03,743 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: defer
2024-04-23 21:59:03,743 INFO    HandlerThread:6140 [handler.py:handle_request_defer():172] handle defer: 9
2024-04-23 21:59:03,744 DEBUG   SenderThread:6140 [sender.py:send():379] send: artifact
2024-04-23 21:59:03,972 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:05,717 INFO    wandb-upload_0:6140 [upload_job.py:push():86] Skipped uploading /Users/a58/Library/Application Support/wandb/artifacts/staging/tmpbpmnvswv
2024-04-23 21:59:06,124 INFO    wandb-upload_1:6140 [upload_job.py:push():89] Uploaded file /var/folders/0t/wpjq3m9x0s39k2ngjkd8dqj80000gn/T/tmp7v09xyim/wandb-job.json
2024-04-23 21:59:07,980 INFO    SenderThread:6140 [sender.py:send_artifact():1468] sent artifact job-https___github.com_Darrenzeng_MoE_Train.git_finetune_run.py - {'id': 'QXJ0aWZhY3Q6ODA3MDM0Mzg1', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjE2MjQ2MjE0MQ==', 'latestArtifact': {'id': 'QXJ0aWZhY3Q6Nzk3MzYwNDUw', 'versionIndex': 2}}}
2024-04-23 21:59:07,981 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: defer
2024-04-23 21:59:07,982 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status_report
2024-04-23 21:59:07,982 INFO    SenderThread:6140 [sender.py:send_request_defer():610] handle sender defer: 9
2024-04-23 21:59:07,983 INFO    SenderThread:6140 [dir_watcher.py:finish():358] shutting down directory watcher
2024-04-23 21:59:08,186 INFO    SenderThread:6140 [dir_watcher.py:finish():388] scan: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files
2024-04-23 21:59:08,186 INFO    SenderThread:6140 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/requirements.txt requirements.txt
2024-04-23 21:59:08,187 INFO    SenderThread:6140 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/output.log output.log
2024-04-23 21:59:08,187 INFO    SenderThread:6140 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/config.yaml config.yaml
2024-04-23 21:59:08,187 INFO    SenderThread:6140 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/wandb-summary.json wandb-summary.json
2024-04-23 21:59:08,187 INFO    SenderThread:6140 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/conda-environment.yaml conda-environment.yaml
2024-04-23 21:59:08,187 INFO    SenderThread:6140 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/wandb-metadata.json wandb-metadata.json
2024-04-23 21:59:08,188 INFO    SenderThread:6140 [sender.py:transition_state():614] send defer: 10
2024-04-23 21:59:08,188 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:08,188 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: defer
2024-04-23 21:59:08,188 INFO    HandlerThread:6140 [handler.py:handle_request_defer():172] handle defer: 10
2024-04-23 21:59:08,188 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: defer
2024-04-23 21:59:08,189 INFO    SenderThread:6140 [sender.py:send_request_defer():610] handle sender defer: 10
2024-04-23 21:59:08,194 INFO    SenderThread:6140 [file_pusher.py:finish():172] shutting down file pusher
2024-04-23 21:59:08,655 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/output.log?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WQw1n4RYT60kmAbdXxMyYzIEdz9QM2R74yq0ynkT03xQqvBQVeEvP4ChgK%2BWpiDRA6scayoVKu%2F3bKcLiwuBTfGLsjLSWF6MqmHCaj2KV4RXg%2FsxukwMw6TIhTWyCMUoM9sMrHhMbvb7KJCbrSFAImhAokhWBxscgjrv8%2Fs4R5hZT7EZm4nf%2F90%2Fml6QHLMr02w06zUqDbNa0p585mrv07tH3%2B%2FR5%2BTOT7x4I%2B%2FPM2Fh53IEJtkkXVsGZkOdENDxM4lkEY49ug4AEEMHb4m0liOTGGxx8egs1OuPHp4aXPu4Fw%2BmL1WcYDRjGnRgtjiCdlYXMXENuc%2F1p0REvZRIhQ%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:08,655 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5490'}
2024-04-23 21:59:08,655 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:08,775 ERROR   wandb-upload_2:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/config.yaml?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QVFQdpZOhF6KnDk536GZ%2BDigE9NjogpEcoZxZvgsw5%2B%2FBMUNatTEzu0O1aI2xBofBO9vaEwi8hUh%2Bscy%2BLxMVKRqUqgUSVeBv11n0VPV3heyh5RrzGVA%2BjfIOvlFjojkdiDNe7LTrtW%2B%2BD1LzXRUsv5mgJ23LqkOkldIgg1rjRgMopoev5sepyHJEApipQXiAcHPmnn9pB8ZtlWQiiz8ZbyXIxCuv1laBGpqjfQ1lqd3VrFBAj6uXbbkVoxc4TGgyEuqDyeERbL07%2Fq7TiQvKY%2BJVmzCxRme82ycrRLXJTexfligPFINjyhoPlNtXNHVSM8ikIOhspbkRsIt6PgzHw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:08,775 ERROR   wandb-upload_2:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '10221'}
2024-04-23 21:59:08,775 ERROR   wandb-upload_2:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:08,778 INFO    wandb-upload_0:6140 [upload_job.py:push():131] Uploaded file /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/requirements.txt
2024-04-23 21:59:08,778 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/conda-environment.yaml?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nzk0ykmHpig25l2dTPM2GdYRs0DGdCc%2Bo0gJmxoCgXzaJCcyALBzAS7ezLnzyDkHRHgCkXLYXz%2BAUzJb7TXd4LmxUYbTHqOeAbswREDs%2BLP2kshw88FXsyo9gQPyYeYKPnQseEdu%2FhkIogcPNehNfg4vr1MlLZUjBZ6MfMW0wKpv9ezvW1g2PIci3xwyZiE6COEFL1b8VwiaY86cyV6GKME0cptO9QvFAOsiAldRR16XsGgxTkFnJYydfqQxfRmsui2rVYq5DANlYhwMAoJvUG9VBuuPXruBTkv9TsTtp98DqpeH8ncsS43CUkxbn1SwDS2HM2pyiAnT6JUTPu949A%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:08,778 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9601'}
2024-04-23 21:59:08,778 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:08,782 ERROR   wandb-upload_3:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/wandb-summary.json?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T1KK5kBTG2Rvkgy95EpwTRVKw%2BZu0ruIDxUz3w35a0%2FR%2FwC5qJzyFDM2Fe7v810QU%2BfUntrSMpsjQ3dV4C4VFIyysLvIj74C6zBu%2FDsq3BUnl%2BgI3uY68GBRncHNPhFMjPXkMZEtgsvs01usDomxcJ80xMvaeLTLcZxiJgPfbFY0BS0pRR4sYmTMfY0pkk5rnbN5C%2FkDfU69qZhFT%2F%2FQ7Q36wn%2F%2FotIGvfss%2FDbpJEbO%2FBqDmlBNsSXEsDROUOvSJ8mUwS9KzMsLdebNSxUwPeLRO3q0d6hVPeojmXJluky0XO6C1mbhJWScNi7jEN1xttPfx8FogcuOTFHWRsK%2BqQ%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:08,782 ERROR   wandb-upload_3:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '27'}
2024-04-23 21:59:08,782 ERROR   wandb-upload_3:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:08,997 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: keepalive
2024-04-23 21:59:08,998 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:08,999 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:09,814 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/output.log?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WQw1n4RYT60kmAbdXxMyYzIEdz9QM2R74yq0ynkT03xQqvBQVeEvP4ChgK%2BWpiDRA6scayoVKu%2F3bKcLiwuBTfGLsjLSWF6MqmHCaj2KV4RXg%2FsxukwMw6TIhTWyCMUoM9sMrHhMbvb7KJCbrSFAImhAokhWBxscgjrv8%2Fs4R5hZT7EZm4nf%2F90%2Fml6QHLMr02w06zUqDbNa0p585mrv07tH3%2B%2FR5%2BTOT7x4I%2B%2FPM2Fh53IEJtkkXVsGZkOdENDxM4lkEY49ug4AEEMHb4m0liOTGGxx8egs1OuPHp4aXPu4Fw%2BmL1WcYDRjGnRgtjiCdlYXMXENuc%2F1p0REvZRIhQ%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:09,815 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5490'}
2024-04-23 21:59:09,815 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:09,815 INFO    wandb-upload_1:6140 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2760, in upload_file
    response = self._upload_file_session.put(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2791, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2760, in upload_file
    response = self._upload_file_session.put(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-04-23 21:59:09,867 ERROR   wandb-upload_2:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/config.yaml?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=QVFQdpZOhF6KnDk536GZ%2BDigE9NjogpEcoZxZvgsw5%2B%2FBMUNatTEzu0O1aI2xBofBO9vaEwi8hUh%2Bscy%2BLxMVKRqUqgUSVeBv11n0VPV3heyh5RrzGVA%2BjfIOvlFjojkdiDNe7LTrtW%2B%2BD1LzXRUsv5mgJ23LqkOkldIgg1rjRgMopoev5sepyHJEApipQXiAcHPmnn9pB8ZtlWQiiz8ZbyXIxCuv1laBGpqjfQ1lqd3VrFBAj6uXbbkVoxc4TGgyEuqDyeERbL07%2Fq7TiQvKY%2BJVmzCxRme82ycrRLXJTexfligPFINjyhoPlNtXNHVSM8ikIOhspbkRsIt6PgzHw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:09,867 ERROR   wandb-upload_2:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '10221'}
2024-04-23 21:59:09,867 ERROR   wandb-upload_2:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:09,867 INFO    wandb-upload_2:6140 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2760, in upload_file
    response = self._upload_file_session.put(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2791, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2760, in upload_file
    response = self._upload_file_session.put(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-04-23 21:59:09,981 ERROR   wandb-upload_3:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/wandb-summary.json?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T1KK5kBTG2Rvkgy95EpwTRVKw%2BZu0ruIDxUz3w35a0%2FR%2FwC5qJzyFDM2Fe7v810QU%2BfUntrSMpsjQ3dV4C4VFIyysLvIj74C6zBu%2FDsq3BUnl%2BgI3uY68GBRncHNPhFMjPXkMZEtgsvs01usDomxcJ80xMvaeLTLcZxiJgPfbFY0BS0pRR4sYmTMfY0pkk5rnbN5C%2FkDfU69qZhFT%2F%2FQ7Q36wn%2F%2FotIGvfss%2FDbpJEbO%2FBqDmlBNsSXEsDROUOvSJ8mUwS9KzMsLdebNSxUwPeLRO3q0d6hVPeojmXJluky0XO6C1mbhJWScNi7jEN1xttPfx8FogcuOTFHWRsK%2BqQ%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:09,981 ERROR   wandb-upload_3:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '27'}
2024-04-23 21:59:09,982 ERROR   wandb-upload_3:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:09,998 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/conda-environment.yaml?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nzk0ykmHpig25l2dTPM2GdYRs0DGdCc%2Bo0gJmxoCgXzaJCcyALBzAS7ezLnzyDkHRHgCkXLYXz%2BAUzJb7TXd4LmxUYbTHqOeAbswREDs%2BLP2kshw88FXsyo9gQPyYeYKPnQseEdu%2FhkIogcPNehNfg4vr1MlLZUjBZ6MfMW0wKpv9ezvW1g2PIci3xwyZiE6COEFL1b8VwiaY86cyV6GKME0cptO9QvFAOsiAldRR16XsGgxTkFnJYydfqQxfRmsui2rVYq5DANlYhwMAoJvUG9VBuuPXruBTkv9TsTtp98DqpeH8ncsS43CUkxbn1SwDS2HM2pyiAnT6JUTPu949A%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:09,998 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9601'}
2024-04-23 21:59:09,998 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:10,003 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:10,004 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:11,005 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:11,006 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:12,012 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:12,012 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:12,317 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/output.log?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WQw1n4RYT60kmAbdXxMyYzIEdz9QM2R74yq0ynkT03xQqvBQVeEvP4ChgK%2BWpiDRA6scayoVKu%2F3bKcLiwuBTfGLsjLSWF6MqmHCaj2KV4RXg%2FsxukwMw6TIhTWyCMUoM9sMrHhMbvb7KJCbrSFAImhAokhWBxscgjrv8%2Fs4R5hZT7EZm4nf%2F90%2Fml6QHLMr02w06zUqDbNa0p585mrv07tH3%2B%2FR5%2BTOT7x4I%2B%2FPM2Fh53IEJtkkXVsGZkOdENDxM4lkEY49ug4AEEMHb4m0liOTGGxx8egs1OuPHp4aXPu4Fw%2BmL1WcYDRjGnRgtjiCdlYXMXENuc%2F1p0REvZRIhQ%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:12,317 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5490'}
2024-04-23 21:59:12,317 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:12,343 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/conda-environment.yaml?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nzk0ykmHpig25l2dTPM2GdYRs0DGdCc%2Bo0gJmxoCgXzaJCcyALBzAS7ezLnzyDkHRHgCkXLYXz%2BAUzJb7TXd4LmxUYbTHqOeAbswREDs%2BLP2kshw88FXsyo9gQPyYeYKPnQseEdu%2FhkIogcPNehNfg4vr1MlLZUjBZ6MfMW0wKpv9ezvW1g2PIci3xwyZiE6COEFL1b8VwiaY86cyV6GKME0cptO9QvFAOsiAldRR16XsGgxTkFnJYydfqQxfRmsui2rVYq5DANlYhwMAoJvUG9VBuuPXruBTkv9TsTtp98DqpeH8ncsS43CUkxbn1SwDS2HM2pyiAnT6JUTPu949A%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:12,344 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9601'}
2024-04-23 21:59:12,344 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:12,591 INFO    wandb-upload_2:6140 [upload_job.py:push():131] Uploaded file /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/config.yaml
2024-04-23 21:59:12,702 ERROR   wandb-upload_3:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/wandb-summary.json?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T1KK5kBTG2Rvkgy95EpwTRVKw%2BZu0ruIDxUz3w35a0%2FR%2FwC5qJzyFDM2Fe7v810QU%2BfUntrSMpsjQ3dV4C4VFIyysLvIj74C6zBu%2FDsq3BUnl%2BgI3uY68GBRncHNPhFMjPXkMZEtgsvs01usDomxcJ80xMvaeLTLcZxiJgPfbFY0BS0pRR4sYmTMfY0pkk5rnbN5C%2FkDfU69qZhFT%2F%2FQ7Q36wn%2F%2FotIGvfss%2FDbpJEbO%2FBqDmlBNsSXEsDROUOvSJ8mUwS9KzMsLdebNSxUwPeLRO3q0d6hVPeojmXJluky0XO6C1mbhJWScNi7jEN1xttPfx8FogcuOTFHWRsK%2BqQ%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:12,703 ERROR   wandb-upload_3:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '27'}
2024-04-23 21:59:12,703 ERROR   wandb-upload_3:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:13,013 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status_report
2024-04-23 21:59:13,017 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:13,018 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:14,024 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:14,026 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:15,027 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:15,027 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:16,030 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:16,031 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:16,734 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/output.log?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WQw1n4RYT60kmAbdXxMyYzIEdz9QM2R74yq0ynkT03xQqvBQVeEvP4ChgK%2BWpiDRA6scayoVKu%2F3bKcLiwuBTfGLsjLSWF6MqmHCaj2KV4RXg%2FsxukwMw6TIhTWyCMUoM9sMrHhMbvb7KJCbrSFAImhAokhWBxscgjrv8%2Fs4R5hZT7EZm4nf%2F90%2Fml6QHLMr02w06zUqDbNa0p585mrv07tH3%2B%2FR5%2BTOT7x4I%2B%2FPM2Fh53IEJtkkXVsGZkOdENDxM4lkEY49ug4AEEMHb4m0liOTGGxx8egs1OuPHp4aXPu4Fw%2BmL1WcYDRjGnRgtjiCdlYXMXENuc%2F1p0REvZRIhQ%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:16,734 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5490'}
2024-04-23 21:59:16,734 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:17,036 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:17,037 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:17,060 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/conda-environment.yaml?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nzk0ykmHpig25l2dTPM2GdYRs0DGdCc%2Bo0gJmxoCgXzaJCcyALBzAS7ezLnzyDkHRHgCkXLYXz%2BAUzJb7TXd4LmxUYbTHqOeAbswREDs%2BLP2kshw88FXsyo9gQPyYeYKPnQseEdu%2FhkIogcPNehNfg4vr1MlLZUjBZ6MfMW0wKpv9ezvW1g2PIci3xwyZiE6COEFL1b8VwiaY86cyV6GKME0cptO9QvFAOsiAldRR16XsGgxTkFnJYydfqQxfRmsui2rVYq5DANlYhwMAoJvUG9VBuuPXruBTkv9TsTtp98DqpeH8ncsS43CUkxbn1SwDS2HM2pyiAnT6JUTPu949A%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:17,060 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9601'}
2024-04-23 21:59:17,060 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:17,477 ERROR   wandb-upload_3:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/wandb-summary.json?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=T1KK5kBTG2Rvkgy95EpwTRVKw%2BZu0ruIDxUz3w35a0%2FR%2FwC5qJzyFDM2Fe7v810QU%2BfUntrSMpsjQ3dV4C4VFIyysLvIj74C6zBu%2FDsq3BUnl%2BgI3uY68GBRncHNPhFMjPXkMZEtgsvs01usDomxcJ80xMvaeLTLcZxiJgPfbFY0BS0pRR4sYmTMfY0pkk5rnbN5C%2FkDfU69qZhFT%2F%2FQ7Q36wn%2F%2FotIGvfss%2FDbpJEbO%2FBqDmlBNsSXEsDROUOvSJ8mUwS9KzMsLdebNSxUwPeLRO3q0d6hVPeojmXJluky0XO6C1mbhJWScNi7jEN1xttPfx8FogcuOTFHWRsK%2BqQ%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:17,478 ERROR   wandb-upload_3:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '27'}
2024-04-23 21:59:17,478 ERROR   wandb-upload_3:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:18,037 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:18,038 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status_report
2024-04-23 21:59:18,039 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:19,044 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:19,046 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:20,052 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:20,054 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:21,060 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:21,061 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:22,064 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:22,065 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:23,072 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status_report
2024-04-23 21:59:23,073 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:23,074 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:24,080 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:24,082 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:25,086 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:25,086 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:25,098 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/output.log?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WQw1n4RYT60kmAbdXxMyYzIEdz9QM2R74yq0ynkT03xQqvBQVeEvP4ChgK%2BWpiDRA6scayoVKu%2F3bKcLiwuBTfGLsjLSWF6MqmHCaj2KV4RXg%2FsxukwMw6TIhTWyCMUoM9sMrHhMbvb7KJCbrSFAImhAokhWBxscgjrv8%2Fs4R5hZT7EZm4nf%2F90%2Fml6QHLMr02w06zUqDbNa0p585mrv07tH3%2B%2FR5%2BTOT7x4I%2B%2FPM2Fh53IEJtkkXVsGZkOdENDxM4lkEY49ug4AEEMHb4m0liOTGGxx8egs1OuPHp4aXPu4Fw%2BmL1WcYDRjGnRgtjiCdlYXMXENuc%2F1p0REvZRIhQ%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:25,098 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5490'}
2024-04-23 21:59:25,098 ERROR   wandb-upload_1:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:25,834 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/b7v20mk3/conda-environment.yaml?Expires=1713967148&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nzk0ykmHpig25l2dTPM2GdYRs0DGdCc%2Bo0gJmxoCgXzaJCcyALBzAS7ezLnzyDkHRHgCkXLYXz%2BAUzJb7TXd4LmxUYbTHqOeAbswREDs%2BLP2kshw88FXsyo9gQPyYeYKPnQseEdu%2FhkIogcPNehNfg4vr1MlLZUjBZ6MfMW0wKpv9ezvW1g2PIci3xwyZiE6COEFL1b8VwiaY86cyV6GKME0cptO9QvFAOsiAldRR16XsGgxTkFnJYydfqQxfRmsui2rVYq5DANlYhwMAoJvUG9VBuuPXruBTkv9TsTtp98DqpeH8ncsS43CUkxbn1SwDS2HM2pyiAnT6JUTPu949A%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-23 21:59:25,835 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9601'}
2024-04-23 21:59:25,835 ERROR   wandb-upload_4:6140 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-23 21:59:26,091 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:26,092 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:26,109 INFO    wandb-upload_3:6140 [upload_job.py:push():131] Uploaded file /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/wandb-summary.json
2024-04-23 21:59:27,097 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:27,098 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:28,104 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:28,105 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: status_report
2024-04-23 21:59:28,105 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:29,110 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:29,111 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:30,116 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:30,119 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:31,089 WARNING StreamThr :6140 [internal.py:is_dead():414] Internal process exiting, parent pid 5901 disappeared
2024-04-23 21:59:31,089 ERROR   StreamThr :6140 [internal.py:wandb_internal():152] Internal process shutdown.
2024-04-23 21:59:31,121 DEBUG   HandlerThread:6140 [handler.py:handle_request():146] handle_request: poll_exit
2024-04-23 21:59:31,122 INFO    HandlerThread:6140 [handler.py:finish():866] shutting down handler
2024-04-23 21:59:31,125 INFO    WriterThread:6140 [datastore.py:close():296] close: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/run-b7v20mk3.wandb
2024-04-23 21:59:31,125 DEBUG   SenderThread:6140 [sender.py:send_request():406] send_request: poll_exit
2024-04-23 21:59:31,126 INFO    SenderThread:6140 [sender.py:finish():1546] shutting down sender
2024-04-23 21:59:31,126 INFO    SenderThread:6140 [file_pusher.py:finish():172] shutting down file pusher
2024-04-23 21:59:31,127 INFO    SenderThread:6140 [file_pusher.py:join():178] waiting for file pusher
2024-04-23 21:59:42,054 INFO    wandb-upload_1:6140 [upload_job.py:push():131] Uploaded file /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/output.log
2024-04-23 21:59:45,654 INFO    wandb-upload_4:6140 [upload_job.py:push():131] Uploaded file /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240423_215815-b7v20mk3/files/conda-environment.yaml
2024-04-23 21:59:45,858 INFO    Thread-16 (_thread_body):6140 [sender.py:transition_state():614] send defer: 11
2024-04-23 21:59:46,226 INFO    SenderThread:6140 [file_stream.py:finish():614] file stream finish called
2024-04-23 21:59:46,486 INFO    SenderThread:6140 [file_stream.py:finish():618] file stream finish is done
